
import { 
  LayoutDashboard, 
  Users, 
  FileText, 
  ArrowDownCircle, 
  Pill, 
  CreditCard,
  BookOpen, 
  BarChart3, 
  Settings 
} from 'lucide-react';
import { MenuItem, Psalm } from './types';

export const MENU_ITEMS: MenuItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, path: '/' },
  { id: 'fornecedores', label: 'Fornecedores', icon: Users, path: '/fornecedores' },
  { id: 'nafs', label: 'NAF\'s', icon: FileText, path: '/nafs' },
  { id: 'medicamentos', label: 'Medicamentos', icon: Pill, path: '/medicamentos' },
  { id: 'baixas', label: 'Baixas', icon: ArrowDownCircle, path: '/baixas' },
  { id: 'folhear', label: 'Folhear Caderno', icon: BookOpen, path: '/folhear' },
  { id: 'cobrancas', label: 'Cobrança', icon: CreditCard, path: '/cobrancas' },
  { id: 'relatorios', label: 'Relatórios', icon: BarChart3, path: '/relatorios' },
  { id: 'administracao', label: 'Administração', icon: Settings, path: '/administracao' },
];

export const PSALMS_DATA: Psalm[] = [
  { id: 1, number: 1, text: "Bem-aventurado o homem que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores." },
  { id: 2, number: 2, text: "Por que se amotinam os gentios, e os povos imaginam coisas vazias? Os reis da terra se levantam e os governos consultam juntamente contra o Senhor." },
  { id: 3, number: 3, text: "Senhor, como se têm multiplicado os meus adversários! São muitos os que se levantam contra mim." },
  { id: 4, number: 4, text: "Ouve-me quando eu clamo, ó Deus da minha justiça, na angústia me deste largueza; tem misericórdia de mim e ouve a minha oração." },
  { id: 5, number: 5, text: "Dá ouvidos às minhas palavras, ó Senhor, atende à minha meditação. Atende à voz do meu clamor, Rei meu e Deus meu, pois a ti orarei." },
  { id: 6, number: 6, text: "Senhor, não me repreendas na tua ira, nem me castigues no teu furor. Tem misericórdia de mim, Senhor, porque sou fraco." },
  { id: 7, number: 7, text: "Senhor meu Deus, em ti confio; salva-me de todos os que me perseguem, e livra-me; para que ele não arrebate a minha alma." },
  { id: 8, number: 8, text: "Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra, pois puseste a tua glória sobre os céus!" },
  { id: 9, number: 9, text: "Eu te louvarei, Senhor, com todo o meu coração; contarei todas as tuas maravilhas." },
  { id: 10, number: 10, text: "Por que te deténs de longe, Senhor? Por que te escondes nos tempos de angústia?" },
  { id: 11, number: 11, text: "No Senhor confio; como dizeis à minha alma: Fugi para a vossa montanha como pássaro?" },
  { id: 12, number: 12, text: "Salva-nos, Senhor, porque faltam os homens bons; porque são poucos os fiéis entre os filhos dos homens." },
  { id: 13, number: 13, text: "Até quando te esquecerás de mim, Senhor? Para sempre? Até quando esconderás de mim o teu rosto?" },
  { id: 14, number: 14, text: "Disseram os néscios no seu coração: Não há Deus. Corromperam-se, tornaram-se abomináveis em suas obras." },
  { id: 15, number: 15, text: "Senhor, quem habitará no teu tabernáculo? Quem morará no teu santo monte? Aquele que anda sinceramente, e pratica a justiça." },
  { id: 16, number: 16, text: "Guarda-me, ó Deus, porque em ti confio. A minha alma disse ao Senhor: Tu és o meu Senhor, a minha bondade não chega a ti." },
  { id: 17, number: 17, text: "Ouve, Senhor, a justiça; atende ao meu clamor; dá ouvidos à minha oração, que não é feita com lábios enganosos." },
  { id: 18, number: 18, text: "Eu te amarei, ó Senhor, fortaleza minha. O Senhor é o meu rochedo, a minha fortaleza e o meu libertador." },
  { id: 19, number: 19, text: "Os céus declaram a glória de Deus e o firmamento anuncia a obra das suas mãos." },
  { id: 20, number: 20, text: "O Senhor te ouça no dia da angústia, o nome do Deus de Jacó te proteja." },
  { id: 21, number: 21, text: "O rei se alegra em tua força, Senhor; e na tua salvação grandemente se regozija." },
  { id: 22, number: 22, text: "Deus meu, Deus meu, por que me desamparaste? Por que te afastas das palavras do meu bramido?" },
  { id: 23, number: 23, text: "O Senhor é o meu pastor, nada me faltará. Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas." },
  { id: 24, number: 24, text: "Do Senhor é a terra e a sua plenitude, o mundo e aqueles que nele habitam." },
  { id: 25, number: 25, text: "A ti, Senhor, levanto a minha alma. Deus meu, em ti confio, não me deixes confundido." },
  { id: 26, number: 26, text: "Julga-me, Senhor, pois tenho andado na minha sinceridade; tenho confiado também no Senhor." },
  { id: 27, number: 27, text: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?" },
  { id: 28, number: 28, text: "A ti clamarei, ó Senhor, rocha minha; não mudes o teu silêncio para comigo; para que não sejas como os que descem à cova." },
  { id: 29, number: 29, text: "Dai ao Senhor, ó filhos dos poderosos, dai ao Senhor glória e força." },
  { id: 30, number: 30, text: "Exaltar-te-ei, ó Senhor, porque tu me levantaste e não permitiste que os meus inimigos se alegrassem sobre mim." },
  { id: 31, number: 31, text: "Em ti, Senhor, confio; nunca me deixes confundido; livra-me pela tua justiça." },
  { id: 32, number: 32, text: "Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto." },
  { id: 33, number: 33, text: "Regozijai-vos no Senhor, vós justos, pois aos retos convém o louvor." },
  { id: 34, number: 34, text: "Louvarei ao Senhor em todo o tempo; o seu louvor estará continuamente na minha boca." },
  { id: 35, number: 35, text: "Pleiteia, Senhor, com os que pleiteiam comigo; peleja contra os que pelejam contra mim." },
  { id: 36, number: 36, text: "A transgressão do ímpio diz no íntimo do meu coração: Não há temor de Deus perante os seus olhos." },
  { id: 37, number: 37, text: "Não te indignes por causa dos malfeitores, nem tenhas inveja dos que praticam a iniqüidade." },
  { id: 38, number: 38, text: "Ó Senhor, não me repreendas na tua ira, nem me castigues no teu furor." },
  { id: 39, number: 39, text: "Eu disse: Guardarei os meus caminhos para não pecar com a minha língua; guardarei a minha boca com um freio." },
  { id: 40, number: 40, text: "Esperei com paciência no Senhor, e ele se inclinou para mim, e ouviu o meu clamor." },
  { id: 41, number: 41, text: "Bem-aventurado é aquele que atende ao pobre; o Senhor o livrará no dia do mal." },
  { id: 42, number: 42, text: "Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus!" },
  { id: 43, number: 43, text: "Faze-me justiça, ó Deus, e pleiteia a minha causa contra a gente impiedosa. Livra-me do homem fraudulento e injusto." },
  { id: 44, number: 44, text: "Ó Deus, nós ouvimos com os nossos ouvidos, e nossos pais nos contaram a obra que fizeste em seus dias." },
  { id: 45, number: 45, text: "O meu coração ferve com palavras boas, falo do que tenho feito no tocante ao Rei. A minha língua é a pena de um destro escritor." },
  { id: 46, number: 46, text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." },
  { id: 47, number: 47, text: "Batei palmas, todos os povos; celebrai a Deus com vozes de júbilo." },
  { id: 48, number: 48, text: "Grande é o Senhor e mui digno de louvor, na cidade do nosso Deus, no seu monte santo." },
  { id: 49, number: 49, text: "Ouvi isto, vós todos os povos; inclinai os ouvidos, todos os moradores do mundo." },
  { id: 50, number: 50, text: "O Deus poderoso, o Senhor, falou e chamou a terra desde o nascimento do sol até ao seu ocaso." },
  { id: 51, number: 51, text: "Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias." },
  { id: 52, number: 52, text: "Por que te glorias na malícia, ó homem poderoso? A bondade de Deus dura continuamente." },
  { id: 53, number: 53, text: "Disse o néscio no seu coração: Não há Deus. Corromperam-se, e cometeram abominável iniqüidade; não há ninguém que faça o bem." },
  { id: 54, number: 54, text: "Salva-me, ó Deus, pelo teu nome, e faze-me justiça pelo teu poder." },
  { id: 55, number: 55, text: "Dá ouvidos, ó Deus, à minha oração, e não te escondas da minha súplica." },
  { id: 56, number: 56, text: "Tem misericórdia de mim, ó Deus, porque o homem procura devorar-me; pelejando todo o dia, me oprime." },
  { id: 57, number: 57, text: "Tem misericórdia de mim, ó Deus, tem misericórdia de mim, porque a minha alma confia em ti; e à sombra das tuas asas me abrigo." },
  { id: 58, number: 58, text: "Falais deveras, ó congregação, a justiça? Julgais retamente, ó filhos dos homens?" },
  { id: 59, number: 59, text: "Livra-me, meu Deus, dos meus inimigos; defende-me daqueles que se levantam contra mim." },
  { id: 60, number: 60, text: "Ó Deus, tu nos rejeitaste, tu nos espalhaste, tu estiveste indignado; oh, volta-te para nós." },
  { id: 61, number: 61, text: "Ouve, ó Deus, o meu clamor; atende à minha oração." },
  { id: 62, number: 62, text: "A minha alma descansa somente em Deus; dele vem a minha salvação." },
  { id: 63, number: 63, text: "Ó Deus, tu és o meu Deus, de madrugada te buscarei; a minha alma tem sede de ti." },
  { id: 64, number: 64, text: "Ouve, ó Deus, a minha voz na minha oração; guarda a minha vida do temor do inimigo." },
  { id: 65, number: 65, text: "A ti, ó Deus, pertence o louvor em Sião, e a ti se pagará o voto." },
  { id: 66, number: 66, text: "Celebrai a Deus com júbilo, todas as terras. Cantai a glória do seu nome; dai glória ao seu louvor." },
  { id: 67, number: 67, text: "Deus tenha misericórdia de nós e nos abençoe; e faça resplandecer o seu rosto sobre nós." },
  { id: 68, number: 68, text: "Levante-se Deus, e sejam dissipados os seus inimigos; fugirão de diante dele os que o odeiam." },
  { id: 69, number: 69, text: "Salva-me, ó Deus, pois as águas entraram até à minha alma." },
  { id: 70, number: 70, text: "Apressa-te, ó Deus, em me livrar; Senhor, apressa-te em ajudar-me." },
  { id: 71, number: 71, text: "Em ti, Senhor, confio; nunca seja eu confundido." },
  { id: 72, number: 72, text: "Ó Deus, dá ao rei os teus juízos, e a tua justiça ao filho do rei." },
  { id: 73, number: 73, text: "Verdadeiramente bom é Deus para com Israel, para com os limpos de coração." },
  { id: 74, number: 74, text: "Ó Deus, por que nos rejeitaste para sempre? Por que se acende a tua ira contra as ovelhas do teu pasto?" },
  { id: 75, number: 75, text: "A ti, ó Deus, rendemos graças, rendemos graças, pois o teu nome está perto." },
  { id: 76, number: 76, text: "Conhecido é Deus em Judá; grande é o seu nome em Israel." },
  { id: 77, number: 77, text: "Clamei a Deus com a minha voz, a Deus levantei a minha voz, e ele inclinou para mim os ouvidos." },
  { id: 78, number: 78, text: "Escutai a minha lei, povo meu; inclinai os vossos ouvidos às palavras da minha boca." },
  { id: 79, number: 79, text: "Ó Deus, as nações entraram na tua herança; contaminaram o teu santo templo; reduziram Jerusalém a montões de pedras." },
  { id: 80, number: 80, text: "Tu, que és pastor de Israel, dá ouvidos; tu, que guias a José como a um rebanho." },
  { id: 81, number: 81, text: "Cantai alegremente a Deus, nossa fortaleza; celebrai ao Deus de Jacó." },
  { id: 82, number: 82, text: "Deus assiste na congregação dos poderosos; julga no meio dos deuses." },
  { id: 83, number: 83, text: "Ó Deus, não estejas em silêncio; não te cales, nem te aquietes, ó Deus." },
  { id: 84, number: 84, text: "Quão amáveis são os teus tabernáculos, Senhor dos Exércitos! A minha alma está desejosa, e desfalece pelos átrios do Senhor." },
  { id: 85, number: 85, text: "Abençoaste, Senhor, a tua terra; fizeste voltar o cativeiro de Jacó." },
  { id: 86, number: 86, text: "Inclina, Senhor, os teus ouvidos, e ouve-me, porque estou necessitado e aflito." },
  { id: 87, number: 87, text: "O seu fundamento está nos montes santos. O Senhor ama as portas de Sião, mais do que todas as habitações de Jacó." },
  { id: 88, number: 88, text: "Senhor Deus da minha salvação, diante de ti tenho clamado de dia e de noite." },
  { id: 89, number: 89, text: "Cantarei para sempre as misericórdias do Senhor; com a minha boca manifestarei a tua fidelidade de geração em geração." },
  { id: 90, number: 90, text: "Senhor, tu tens sido o nosso refúgio, de geração em geração." },
  { id: 91, number: 91, text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. Direi do Senhor: Ele é o meu Deus, o meu refúgio, a minha fortaleza, e nele confiarei." },
  { id: 92, number: 92, text: "Bom é louvar ao Senhor, e cantar louvores ao teu nome, ó Altíssimo; para de manhã anunciar a tua benignidade, e todas as noites a tua fidelidade." },
  { id: 93, number: 93, text: "O Senhor reina; está vestido de majestade. O Senhor se revestiu e cingiu de poder." },
  { id: 94, number: 94, text: "Ó Senhor Deus, a quem a vingança pertence, ó Deus, a quem a vingança pertence, mostra-te resplandecente." },
  { id: 95, number: 95, text: "Vinde, cantemos ao Senhor; jubilemos à rocha da nossa salvação." },
  { id: 96, number: 96, text: "Cantai ao Senhor um cântico novo, cantai ao Senhor todas as terras." },
  { id: 97, number: 97, text: "O Senhor reina; regozije-se a terra; alegrem-se as muitas ilhas." },
  { id: 98, number: 98, text: "Cantai ao Senhor um cântico novo, porque fez maravilhas; a sua destra e o seu braço santo lhe alcançaram a vitória." },
  { id: 99, number: 99, text: "O Senhor reina; tremam os povos. Ele está assentado entre os querubins; comova-se a terra." },
  { id: 100, number: 100, text: "Celebrai com júbilo ao Senhor, todas as terras. Servi ao Senhor com alegria; e apresentai-vos a ele com canto." },
  { id: 101, number: 101, text: "Cantarei a misericórdia e o juízo; a ti, Senhor, cantarei." },
  { id: 102, number: 102, text: "Senhor, ouve a minha oração, e chegue a ti o meu clamor. Não escondas de mim o teu rosto no dia da minha angústia." },
  { id: 103, number: 103, text: "Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome." },
  { id: 104, number: 104, text: "Bendize, ó minha alma, ao Senhor! Senhor Deus meu, tu és magnificentíssimo; estás vestido de glória e de majestade." },
  { id: 105, number: 105, text: "Louvai ao Senhor, e invocai o seu nome; fazei conhecidas as suas obras entre os povos." },
  { id: 106, number: 106, text: "Louvai ao Senhor. Louvai ao Senhor, porque ele é bom, porque a sua misericórdia dura para sempre." },
  { id: 107, number: 107, text: "Louvai ao Senhor, porque ele é bom, porque a sua misericórdia dura para sempre. Digam-no os remidos do Senhor." },
  { id: 108, number: 108, text: "Preparado está o meu coração, ó Deus; cantarei e darei louvores até com a minha glória." },
  { id: 109, number: 109, text: "Ó Deus do meu louvor, não te cales, pois a boca do ímpio e a boca do enganador se abriram contra mim." },
  { id: 110, number: 110, text: "Disse o Senhor ao meu Senhor: Assenta-te à minha direita, até que ponha os teus inimigos por escabelo de teus pés." },
  { id: 111, number: 111, text: "Louvai ao Senhor. Louvarei ao Senhor de todo o meu coração, na assembléia dos retos e na congregação." },
  { id: 112, number: 112, text: "Louvai ao Senhor. Bem-aventurado o homem que teme ao Senhor, que em seus mandamentos tem grande prazer." },
  { id: 113, number: 113, text: "Louvai ao Senhor. Louvai, servos do Senhor, louvai o nome do Senhor." },
  { id: 114, number: 114, text: "Quando Israel saiu do Egito, e a casa de Jacó de um povo de língua estranha, Judá foi seu santuário, e Israel seu domínio." },
  { id: 115, number: 115, text: "Não a nós, Senhor, não a nós, mas ao teu nome dá glória, por amor da tua misericórdia e da tua fidelidade." },
  { id: 116, number: 116, text: "Amo ao Senhor, porque ele ouviu a minha voz e a minha súplica." },
  { id: 117, number: 117, text: "Louvai ao Senhor todas as nações, louvai-o todos os povos. Porque a sua benignidade é grande para conosco." },
  { id: 118, number: 118, text: "Louvai ao Senhor, porque ele é bom; porque a sua misericórdia dura para sempre." },
  { id: 119, number: 119, text: "Bem-aventurados os que trilham caminhos retos, e andam na lei do Senhor. Lâmpada para os meus pés é tua palavra, e luz para o meu caminho." },
  { id: 120, number: 120, text: "Na minha angústia clamei ao Senhor, e ele me ouviu. Senhor, livra a minha alma dos lábios mentirosos e da língua enganadora." },
  { id: 121, number: 121, text: "Elevo os meus olhos para os montes; de onde me vem o socorro? O meu socorro vem do Senhor, que fez o céu e a terra." },
  { id: 122, number: 122, text: "Alegrei-me quando me disseram: Vamos à casa do Senhor. Os nossos pés estão dentro das tuas portas, ó Jerusalém." },
  { id: 123, number: 123, text: "A ti levanto os meus olhos, ó tu que habitas nos céus. Assim como os olhos dos servos atentam para as mãos dos seus senhores." },
  { id: 124, number: 124, text: "Se não fora o Senhor, que esteve ao nosso lado, ora diga Israel; se não fora o Senhor, que esteve ao nosso lado, quando os homens se levantaram contra nós." },
  { id: 125, number: 125, text: "Os que confiam no Senhor serão como o monte de Sião, que não se abala, mas permanece para sempre." },
  { id: 126, number: 126, text: "Quando o Senhor trouxe do cativeiro os que voltaram a Sião, estávamos como os que sonham. Então a nossa boca se encheu de riso." },
  { id: 127, number: 127, text: "Se o Senhor não edificar a casa, em vão trabalham os que a edificam; se o Senhor não guardar a cidade, em vão vigia a sentinela." },
  { id: 128, number: 128, text: "Bem-aventurado aquele que teme ao Senhor e anda nos seus caminhos. Do trabalho das tuas mãos comerás; feliz serás, e te irá bem." },
  { id: 129, number: 129, text: "Muitas vezes me angustiaram desde a minha mocidade, diga agora Israel; muitas vezes me angustiaram desde a minha mocidade; todavia não prevaleceram contra mim." },
  { id: 130, number: 130, text: "Das profundezas a ti clamo, ó Senhor. Senhor, ouve a minha voz; sejam os teus ouvidos atentos à voz das minhas súplicas." },
  { id: 131, number: 131, text: "Senhor, o meu coração não se elevou nem os meus olhos se levantaram; não me exercito em grandes assuntos, nem em coisas muito elevadas para mim." },
  { id: 132, number: 132, text: "Lembra-te, Senhor, de Davi, e de todas as suas aflições. Como jurou ao Senhor, e fez votos ao Poderoso de Jacó." },
  { id: 133, number: 133, text: "Oh! quão bom e quão suave é que os irmãos vivam em união. É como o óleo precioso sobre a cabeça, que desce sobre a barba." },
  { id: 134, number: 134, text: "Eis aqui, bendizei ao Senhor todos vós, servos do Senhor, que assistis na casa do Senhor todas as noites." },
  { id: 135, number: 135, text: "Louvai ao Senhor. Louvai o nome do Senhor; louvai-o, servos do Senhor. Vós que assistis na casa do Senhor, nos átrios da casa do nosso Deus." },
  { id: 136, number: 136, text: "Louvai ao Senhor, porque ele é bom; porque a sua misericórdia dura para sempre. Louvai ao Deus dos deuses; porque a sua misericórdia dura para sempre." },
  { id: 137, number: 137, text: "Junto aos rios da Babilônia, ali nos assentamos e choramos, recordando-nos de Sião. Nos salgueiros, no meio dela, penduramos as nossas harpas." },
  { id: 138, number: 138, text: "Render-te-ei graças, Senhor, de todo o meu coração; na presença dos deuses a ti cantarei louvores." },
  { id: 139, number: 139, text: "Senhor, tu me sondaste, e me conheces. Tu sabes o meu assentar e o meu levantar; de longe entendes o meu pensamento." },
  { id: 140, number: 140, text: "Livra-me, ó Senhor, do homem mau; guarda-me do homem violento, que imagina males no coração; continuamente se ajuntam para a guerra." },
  { id: 141, number: 141, text: "Senhor, a ti clamo, apressa-te em me socorrer; dá ouvidos à minha voz, quando a ti clamar. Suba a minha oração perante a tua face como incenso." },
  { id: 142, number: 142, text: "Com a minha voz clamei ao Senhor; com a minha voz supliquei ao Senhor. Derramei a minha queixa perante a sua face; expus diante dele a minha tribulação." },
  { id: 143, number: 143, text: "Ó Senhor, ouve a minha oração, inclina os ouvidos às minhas súplicas; responde-me segundo a tua fidelidade e segundo a tua justiça." },
  { id: 144, number: 144, text: "Bendito seja o Senhor, minha rocha, que ensina as minhas mãos para a peleja e os meus dedos para a guerra." },
  { id: 145, number: 145, text: "Exaltar-te-ei, ó Deus, Rei meu, e bendirei o teu nome pelos séculos dos séculos e para sempre." },
  { id: 146, number: 146, text: "Louvai ao Senhor. Ó minha alma, louva ao Senhor. Louvarei ao Senhor durante a minha vida; cantarei louvores ao meu Deus enquanto eu viver." },
  { id: 147, number: 147, text: "Louvai ao Senhor, porque é bom cantar louvores ao nosso Deus, porque é agradável; decoroso é o louvor." },
  { id: 148, number: 148, text: "Louvai ao Senhor. Louvai ao Senhor desde os céus, louvai-o nas alturas. Louvai-o, todos os seus anjos; louvai-o, todos os seus exércitos." },
  { id: 149, number: 149, text: "Louvai ao Senhor. Cantai ao Senhor um cântico novo, e o seu louvor na congregação dos santos. Alegre-se Israel naquele que o fez." },
  { id: 150, number: 150, text: "Louvai ao Senhor. Louvai a Deus no seu santuário; louvai-o no firmamento do seu poder. Louvai-o pelos seus atos poderosos. Tudo quanto tem fôlego louve ao Senhor." },
];

// Helper para obter todos os salmos (retorna a base estática agora completa)
export const getAllPsalms = (): Psalm[] => {
    return PSALMS_DATA;
};
